type User {
  _id: ID!
  first_name: String!
  last_name: String
  full_name: String
  email: String!
  isActive: Boolean!
}

type Query {
  users: [User!]!
  user(id: ID!): User!
}

input UserInput {
  first_name: String!
  last_name: String
  email: String!
  isActive: Boolean!
}

type Mutation {
  createUser(data: UserInput): User!
  updateUser(id: ID!, data: UserInput): User!
  deleteUser(id: ID!): Boolean
}

type Subscription {
  userAdded: User!
}
